name: Jupyter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - id: repo 
        name: Repo Checkout
        uses: actions/checkout@v2

      - id: python
        name: Python Setup & Packages Installation
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - id: jupyter 
        name: Jupyter Notebook Execution
        run: jupyter execute main.ipynb
        shell: bash

      - name: Create branch and commit changes
        run: |
          git checkout -b automated-branch
          # Make changes to the files, for example:
          # echo "Automated change" >> main.ipynb
          git add .
          git commit -m "Automated commit"
          git push origin automated-branch

      - name: Create Pull Request
        run: |
          gh pr create --base main --head automated-branch --title "Automated PR" --body "This is an automated PR"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

